accounts/urls.py
from django.urls import path
from . import views 

app_name = 'accounts'


urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('signup/', views.signup_view, name = 'signup'),
    path('logout/', views.logout_view, name = 'logout')
    
]

articles/urls.py
from django.urls import path
from . import views 

app_name = "articles"

urlpatterns = [
    path('', views.index, name='index')
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
    path('', include('articles.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render

def login_view(request):
    return render(request, 'accounts/login.html', {})

def signup_view(request):
    return render(request, 'accounts/signup.html', {})

def logout_view(request):
    return render(request, 'accounts/logout.html', {})

articles/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'articles/index.html', {})

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{%  block content %}
<h1>This is login page </h1>
{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'base.html' %}

{% block content  %}
<h1>This is logout page </h1>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{%  block content %}
<h1>This is signup page </h1>
{% endblock %}

articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content  %}

<h1>This is home page</h1>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <title>Document</title>
</head>
<body>
    <div class="wrapper"> 
        <nav>
            <ul>
                <li><a href="{% url 'accounts:login' %}">Login</a></li>
                <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                <li><a href="{% url 'accounts:signup' %}">SignUp</a></li>
            </ul>
            <ul>
                
                <li><a href="{% url 'articles:index' %}">Home</a></li>
            </ul>
        </nav>
    <h1>This is base template</h1>
    {%  block content %}
    {% endblock %}
    </div>
</body>
</html>